name: todo
description: Udevs Todo app

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.7.0
  fluttertoast: ^8.2.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
      
